apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2023-04-03T18:39:50Z"
  generation: 3938
  name: jenkins
  namespace: argocd
  resourceVersion: "1248979"
  uid: 25e92e36-046d-4760-9b58-edd8d0209fde
spec:
  destination:
    namespace: ci-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ci-cd
    repoURL: https://github.com/pluhin/build_sa
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health:
    status: Healthy
  history:
  - deployStartedAt: "2023-04-03T18:39:51Z"
    deployedAt: "2023-04-03T18:39:53Z"
    id: 0
    revision: 982d4fde20f1a02c6ed989ec2dea28ee171d46dc
    source:
      path: ci-cd
      repoURL: https://github.com/pluhin/build_sa
      targetRevision: HEAD
  - deployStartedAt: "2023-04-11T18:06:46Z"
    deployedAt: "2023-04-11T18:06:48Z"
    id: 1
    revision: 982d4fde20f1a02c6ed989ec2dea28ee171d46dc
    source:
      path: ci-cd
      repoURL: https://github.com/pluhin/build_sa
      targetRevision: HEAD
  operationState:
    finishedAt: "2023-04-11T18:06:49Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 982d4fde20f1a02c6ed989ec2dea28ee171d46dc
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2023-04-11T18:06:46Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: 'namespace/ci-cd configured. Warning: resource namespaces/ci-cd is
          missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically.'
        name: ci-cd
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/basic-security created
        name: basic-security
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/jenkins-config created
        name: jenkins-config
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: clusterrolebinding.rbac.authorization.k8s.io/jenkins reconciled.
          clusterrolebinding.rbac.authorization.k8s.io/jenkins unchanged
        name: jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/jenkins created
        name: jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/jenkins created
        name: jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/ingress-jenkins created
        name: ingress-jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 982d4fde20f1a02c6ed989ec2dea28ee171d46dc
      source:
        path: ci-cd
        repoURL: https://github.com/pluhin/build_sa
        targetRevision: HEAD
  reconciledAt: "2023-04-11T20:55:35Z"
  resources:
  - kind: ConfigMap
    name: basic-security
    namespace: ci-cd
    status: Synced
    version: v1
  - kind: ConfigMap
    name: jenkins-config
    namespace: ci-cd
    status: Synced
    version: v1
  - kind: Namespace
    name: ci-cd
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: jenkins
    namespace: ci-cd
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: jenkins
    namespace: ci-cd
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: ingress-jenkins
    namespace: ci-cd
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: jenkins
    status: Synced
    version: v1
  sourceType: Directory
  summary:
    externalURLs:
    - http://jenkins.k8s-20.sa/
    images:
    - jfrog.it-academy.by/public/jenkins-ci:spishchyk
  sync:
    comparedTo:
      destination:
        namespace: ci-cd
        server: https://kubernetes.default.svc
      source:
        path: ci-cd
        repoURL: https://github.com/pluhin/build_sa
        targetRevision: HEAD
    revision: 982d4fde20f1a02c6ed989ec2dea28ee171d46dc
    status: Synced
